---
title: "soybean"
author: "Maxwel Coura Oliveira"
date: "6/2/2020"
output: html_document
---

```{r}
library(tidyverse)
library(tidymodels)
library(ranger)
```


```{r}
data <- read.csv("full_data.csv") %>% 
  mutate_if(is.character, as.factor) 
```


```{r}
skimr::skim(data)
```


```{r}
new_dt <- data %>% 
  select(-ExpUnit, -Entry, -Rep, -Run, -Subsample, -Illevo_Inj) %>% 
  na.omit() %>% 
  mutate(MG = factor(MG))
```


```{r}
set.seed(123)
trees_split <- initial_split(new_dt, strata = Rating)
trees_train <- training(trees_split)
trees_test <- testing(trees_split)
```




```{r}
tree_rec <- recipe(Rating ~., data = trees_train) %>% 
  update_role(Trt, new_role="ID") %>% 
  #step_other(CurrentCrop, PreviousCrop, threshold = 0.01) %>% 
  step_dummy(all_nominal(), -all_outcomes())# %>% 
#  step_downsample(Rating)

#trees_prep <- prep(tree_rec)  #only for factor
#juiced <- juice(trees_prep)
```

```{r}
tune_spec <- rand_forest(
  mtry = tune(),
  trees = 1000,
  min_n = tune()
) %>% 
  set_mode("regression") %>% 
  set_engine("ranger")
```


```{r}
tune_wf <- workflow() %>% 
  add_recipe(tree_rec) %>% 
  add_model(tune_spec)
```

 
# Train

```{r}
set.seed(456)
tree_folds <- vfold_cv(trees_train)
doParallel::registerDoParallel()
set.seed(345)

tune_res <- tune_grid(
  tune_wf,
  resamples = tree_folds,
  grid=20
)
```



